[package]
name = "dreamegg"
version = "0.1.0"
authors = ["Matt Bowers <mattb6503@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egg = "0.6.0"
log = "0.4.0"
env_logger = "0.8.4"
chrono = "0.4"
serde_json = "1.0"
clap = "3.0.0-beta.5"
symbolic_expressions = "5"
nix = "0.23.0"
serde = "1.0.130"
procspawn = "0.10.0"
lazy_static = "1.4.0"